version: '3'
services:
  python:
    container_name: consumption-notifier
    image: rphlct/consumption-notifier
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      MAILGUN_SERVER_NAME: '${MAILGUN_SERVER_NAME}'
      MAILGUN_API_KEY: '${MAILGUN_API_KEY}'
      BELL_LOGIN: '${BELL_LOGIN}'
      BELL_PASSWORD: '${BELL_PASSWORD}'
      BELL_RECIPIENTS: '${BELL_RECIPIENTS}'
      VIDEOTRON_RECIPIENTS: '${VIDEOTRON_RECIPIENTS}'
      FIREFOX_IP: 'selenium-firefox:4444'
    depends_on:
      - selenium-firefox
  selenium-firefox:
    container_name: selenium-firefox
    image: 'selenium/standalone-firefox'
    ports:
      - '4444:4444'